export const AUDIT_ACTIONS = [
  "auth.login_succeeded",
  "auth.login_failed",
  "auth.logout",
  "auth.otp_sent",
  "auth.otp_verified",
  "auth.otp_failed",
  "auth.password_reset_requested",
  "auth.password_reset_completed",
  "user.created",
  "user.deactivated",
  "user.reactivated",
  "user.details_updated",
  "user.role_changed",
  "assignment.branch_started",
  "assignment.branch_ended",
  "assignment.area_started",
  "assignment.area_ended",
  "user.promoted",
  "user.reassigned",
  "user.deleted",
  "loan.created",
  "loan.deleted",
  "loan.status_changed_manual",
  "loan.status_changed_system",
  "loan.collector_changed",
  "collection.recorded",
  "expense.created",
  "document.uploaded",
  "document.deleted",
  "document.replaced",
  "report.generated",
  "report.exported",
  "report.generated_system_monthly",
  "incentive.rule_created",
  "incentive.batch_finalized",
  "incentive.payout_recorded",
  "incentive.report_generated",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_ENTITY_TYPES = [
  "auth",
  "user",
  "assignment",
  "loan",
  "collection",
  "expense",
  "document",
  "report",
  "incentive",
] as const;

export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[number];

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  "auth.login_succeeded": "Login succeeded",
  "auth.login_failed": "Login failed",
  "auth.logout": "Logout",
  "auth.otp_sent": "OTP sent",
  "auth.otp_verified": "OTP verified",
  "auth.otp_failed": "OTP failed",
  "auth.password_reset_requested": "Password reset requested",
  "auth.password_reset_completed": "Password reset completed",
  "user.created": "User created",
  "user.deactivated": "User deactivated",
  "user.reactivated": "User reactivated",
  "user.details_updated": "User details updated",
  "user.role_changed": "User role changed",
  "assignment.branch_started": "Branch assignment started",
  "assignment.branch_ended": "Branch assignment ended",
  "assignment.area_started": "Area assignment started",
  "assignment.area_ended": "Area assignment ended",
  "user.promoted": "User promoted",
  "user.reassigned": "User reassigned",
  "user.deleted": "User deleted",
  "loan.created": "Loan created",
  "loan.deleted": "Loan deleted",
  "loan.status_changed_manual": "Loan status changed manually",
  "loan.status_changed_system": "Loan status changed by system",
  "loan.collector_changed": "Loan collector changed",
  "collection.recorded": "Collection recorded",
  "expense.created": "Expense recorded",
  "document.uploaded": "Document uploaded",
  "document.deleted": "Document deleted",
  "document.replaced": "Document replaced",
  "report.generated": "Report generated",
  "report.exported": "Report exported",
  "report.generated_system_monthly": "System monthly report generated",
  "incentive.rule_created": "Incentive rule created",
  "incentive.batch_finalized": "Incentive batch finalized",
  "incentive.payout_recorded": "Incentive payout recorded",
  "incentive.report_generated": "Incentive report generated",
};

export const AUDIT_ENTITY_LABELS: Record<AuditEntityType, string> = {
  auth: "Auth",
  user: "User",
  assignment: "Assignment",
  loan: "Loan",
  collection: "Collection",
  expense: "Expense",
  document: "Document",
  report: "Report",
  incentive: "Incentive",
};
