import { FileStack } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

export default function LoadingReportsLibraryPage() {
  return (
    <div className="w-full max-w-none space-y-5 pb-6 pt-1 sm:pb-6 sm:pt-2">
      <Card className="gap-0 overflow-hidden py-0">
        <div className="bg-gradient-to-r from-slate-50 via-background to-emerald-50/60 p-6 dark:from-zinc-950 dark:via-background dark:to-emerald-950/45">
          <div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between">
            <div className="space-y-1">
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <FileStack className="size-7 shrink-0 text-muted-foreground" />
                  <Skeleton className="h-9 w-72 max-w-full" />
                </div>
                <Skeleton className="h-4 w-[34rem] max-w-full" />
              </div>

              <div className="flex flex-wrap items-center gap-2 pt-2">
                <Skeleton className="h-8 w-24 rounded-full" />
                <Skeleton className="h-8 w-40 rounded-full" />
              </div>
            </div>

            <Skeleton className="h-9 w-44 rounded-md" />
          </div>
        </div>

        <div className="border-t border-border/70 px-6 pb-4 pt-3">
          <div className="inline-flex flex-wrap gap-2 rounded-xl border border-border/70 bg-muted/30 p-1">
            <Skeleton className="h-9 w-28 rounded-lg" />
            <Skeleton className="h-9 w-24 rounded-lg" />
            <Skeleton className="h-9 w-24 rounded-lg" />
          </div>
        </div>
      </Card>

      <Card>
        <CardHeader className="border-b border-border/60 bg-background">
          <div className="flex items-start gap-3">
            <div className="rounded-xl border border-border/70 bg-background p-2 text-muted-foreground">
              <FileStack className="h-5 w-5" />
            </div>
            <div className="space-y-1">
              <CardTitle>
                <Skeleton className="h-6 w-36" />
              </CardTitle>
              <CardDescription>
                <Skeleton className="h-4 w-[30rem] max-w-full" />
              </CardDescription>
            </div>
          </div>
        </CardHeader>

        <CardContent className="space-y-4">
          <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
            <div className="inline-flex flex-wrap gap-2 rounded-xl border border-border/70 bg-muted/30 p-1">
              <Skeleton className="h-8 w-24 rounded-lg" />
              <Skeleton className="h-8 w-28 rounded-lg" />
            </div>

            <Skeleton className="h-10 w-36 rounded-md" />
          </div>

          <div className="relative space-y-3">
            <div className="overflow-hidden rounded-2xl border border-border/70">
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-border/70">
                  <thead className="bg-muted/20">
                    <tr className="text-left text-sm text-muted-foreground">
                      <th className="px-4 py-3 font-medium">Title</th>
                      <th className="px-4 py-3 font-medium">Generated By</th>
                      <th className="px-4 py-3 font-medium">Generated At</th>
                      <th className="px-4 py-3 font-medium">Status</th>
                      <th className="px-4 py-3 font-medium">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border/60 bg-background">
                    {Array.from({ length: 5 }).map((_, index) => (
                      <tr className="align-middle text-sm" key={index}>
                        <td className="px-4 py-4 align-middle">
                          <div className="space-y-1">
                            <Skeleton className="h-5 w-48" />
                            <Skeleton className="h-4 w-32" />
                          </div>
                        </td>
                        <td className="px-4 py-4 align-middle">
                          <div className="flex flex-wrap items-center gap-2">
                            <Skeleton className="h-6 w-28 rounded-full" />
                            <Skeleton className="h-5 w-40" />
                          </div>
                        </td>
                        <td className="px-4 py-4 align-middle">
                          <Skeleton className="h-5 w-32" />
                        </td>
                        <td className="px-4 py-4 align-middle">
                          <Skeleton className="h-6 w-20 rounded-full" />
                        </td>
                        <td className="px-4 py-4 align-middle">
                          <div className="flex flex-wrap items-center gap-2">
                            <Skeleton className="h-9 w-16 rounded-md" />
                            <Skeleton className="h-9 w-20 rounded-md" />
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            <div className="flex flex-col gap-3 border-t pt-3 text-sm md:flex-row md:items-center md:justify-between">
              <Skeleton className="h-4 w-36" />
              <div className="flex flex-wrap items-center gap-2 xl:justify-center">
                <div className="flex items-center gap-2">
                  <Skeleton className="h-4 w-10" />
                  <Skeleton className="h-9 w-[84px] rounded-md" />
                </div>
                <div className="ml-4 flex items-center gap-2">
                  <Skeleton className="h-4 w-20" />
                  <Skeleton className="h-9 w-9 rounded-md" />
                  <Skeleton className="h-9 w-9 rounded-md" />
                </div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
